update stream.stop() call
stream.stop()has been deprecated. In Chrome 55, this call produces an Uncaught TypeError: this.stream.stop is not a function.

This method call has been changed to the new syntax this.stream.getTracks()[0].stop().